export const translateWeather = () => {
  return {
    none: "Could not find",
    clearsky_day: "Clear Sky",
    clearsky_night: "Clear Sky",
    clearsky_polartwilight: "Clear Sky",
    cloudy: "Cloudy",
    fair_day: "Fair",
    fair_night: "Fair",
    fair_polartwilight: "Fair",
    fog: "Fog",
    heavyrain: "Heavy Rain",
    heavyrainandthunder: "Heavy Rain, Thunder",
    heavyrainshowers_day: "Heavy Rain Showers",
    heavyrainshowers_night: "Heavy Rain Showers",
    heavyrainshowers_polartwilight: "Heavy Rain Showers",
    heavyrainshowersandthunder_day: "Heavy Rain Showers, Thunder",
    heavyrainshowersandthunder_night: "Heavy Rain Showers, Thunder",
    heavyrainshowersandthunder_polartwilight: "Heavy Rain Showers, Thunder",
    heavysleet: "Heavy Sleet",
    heavysleetandthunder: "Heavy Sleet, Thunder",
    heavysleetshowers_day: "Heavy Sleet Showers",
    heavysleetshowers_night: "Heavy Sleet Showers",
    heavysleetshowers_polartwilight: "Heavy Sleet Showers",
    heavysleetshowersandthunder_day: "Heavy Sleet Showers, Thunder",
    heavysleetshowersandthunder_night: "Heavy Sleet Showers, Thunder",
    heavysleetshowersandthunder_polartwilight: "Heavy Sleet Showers, Thunder",
    heavysnow: "Heavy Snow",
    heavysnowandthunder: "Heavy Snow, Thunder",
    heavysnowshowers_day: "Heavy Snow Showers",
    heavysnowshowers_night: "Heavy Snow Showers",
    heavysnowshowers_polartwilight: "Heavy Snow Showers",
    heavysnowshowersandthunder_day: "Heavy Snow Showers, Thunder",
    heavysnowshowersandthunder_night: "Heavy Snow Showers, Thunder",
    heavysnowshowersandthunder_polartwilight: "Heavy Snow Showers, Thunder",
    lightrain: "Light Rain",
    lightrainandthunder: "Light Rain, Thunder",
    lightrainshowers_day: "Light Rain Showers",
    lightrainshowers_night: "Light Rain Showers",
    lightrainshowers_polartwilight: "Light Rain Showers, Thunder",
    lightrainshowersandthunder_day: "Light Rain Showers, Thunder",
    lightrainshowersandthunder_night: "Light Rain Showers, Thunder",
    lightrainshowersandthunder_polartwilight: "Light Rain Showers, Thunder",
    lightsleet: "Light Sleet",
    lightsleetandthunder: "Light Sleet, Thunder",
    lightsleetshowers_day: "Light Sleet Showers",
    lightsleetshowers_night: "Light Sleet Showers",
    lightsleetshowers_polartwilight: "Light Sleet Shower",
    lightsnow: "Light Snow",
    lightsnowandthunder: "Light Snow, Thunder",
    lightsnowshowers_day: "Light Snow Showers",
    lightsnowshowers_night: "Light Snow Showers",
    lightsnowshowers_polartwilight: "Light Snow Showers",
    lightssleetshowersandthunder_day: "Light Sleet Showers, Thunder",
    lightssleetshowersandthunder_night: "Light Sleet Showers, Thunder",
    lightssleetshowersandthunder_polartwilight: "Light Sleet Showers, Thunder",
    lightssnowshowersandthunder_day: "Light Snow Showers, Thunder",
    lightssnowshowersandthunder_night: "Light Snow Showers, Thunder",
    lightssnowshowersandthunder_polartwilight: "Light Snow Showers, Thunder",
    partlycloudy_day: "Partly Cloudy",
    partlycloudy_night: "Partly Cloudy",
    partlycloudy_polartwilight: "Partly Cloudy",
    rain: "Rain",
    rainandthunder: "Rain and Thunder",
    rainshowers_day: "Rain Showers",
    rainshowers_night: "Rain Showers",
    rainshowers_polartwilight: "Rain Showers",
    rainshowersandthunder_day: "Rain Showers, Thunder",
    rainshowersandthunder_night: "Rain Showers, Thunder",
    rainshowersandthunder_polartwilight: "Rain Showers, Thunder",
    sleet: "Sleet",
    sleetandthunder: "Sleet and Thunder",
    sleetshowers_day: "Sleet Showers",
    sleetshowers_night: "Sleet Showers",
    sleetshowers_polartwilight: "Sleet Showers",
    sleetshowersandthunder_day: "Sleet Showers, Thunder",
    sleetshowersandthunder_night: "Sleet Showers, Thunder",
    sleetshowersandthunder_polartwilight: "Sleet Showers, Thunder",
    snow: "Snow",
    snowandthunder: "Snow and Thunder",
    snowshowers_day: "Snow Showers",
    snowshowers_night: "Snow Showers",
    snowshowers_polartwilight: "Snow Showers",
    snowshowersandthunder_day: "Snow Showers, Thunder",
    snowshowersandthunder_night: "Snow Showers, Thunder",
    snowshowersandthunder_polartwilight: "Snow Showers, Thunder",
  };
};
